#pragma once

enum
{
    SOUND_NULL,
    PLAYER_DIE,
    FIREBALL_HIT,
    ROCK_ROLLING,
    NPC_DIE,
    NPC_ENEMY_DETECTED,
    PRESSURE_PLATE_USE,
    LEVER_USE,
    VAMPIRE_ENEMY_DETECTED,
    VAMPIRE_DIE,
    ROCK_HIT,
    DOOR_OPEN,
    DOOR_CLOSE,
    SPURDO_DIE,
    OPEN_INVENTORY,
    SPIDER_ENEMY_DETECTED,
    SPIDER_DIE
};